# Generated by Django 4.0.3 on 2022-03-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0002_alter_budget_options_alter_budgetcolumn_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budget",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
