# Generated by Django 4.0.3 on 2022-03-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0003_alter_budget_end_date_alter_budget_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetitem",
            name="order",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
