# Generated by Django 4.0.3 on 2022-04-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0005_alter_budgetitem_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={"ordering": ["-end_date", "created_at"]},
        ),
    ]
