# Generated by Django 4.0.3 on 2022-04-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0006_alter_budget_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
