# Generated by Django 4.0.3 on 2022-05-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0008_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
